name: news_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  provider: ^6.1.2
  flutter_dotenv: ^6.0.0
  flutter_svg: ^2.2.1
  get_it: ^7.4.0
  go_router: ^16.2.5
  json_annotation: ^4.9.0
  http: ^1.5.0
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.11.1
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
  #   - assets/images/
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
